default_stages: [manual]

repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
        log_file: .flake8.log
        verbose: true
      - id: black
        name: black
        entry: black --check --diff --extend-exclude '.**/*'.
        language: system
        types: [python]
        require_serial: true
        log_file: .black.log
        verbose: true
      - id: isort
        name: isort
        entry: isort --diff .
        language: system
        types: [python]
        require_serial: true
        log_file: .isort.log
        verbose: true
      - id: mypy
        name: mypy
        entry: mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers --no-pretty .
        language: system
        types: [python]
        require_serial: true
        log_file: .mypy.log
        verbose: true
