default_stages: [manual]

repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 project/
        language: system
        types: [python]
        require_serial: true
      - id: black
        name: black
        entry: black project/
        language: system
        types: [python]
        require_serial: true
        log_file: .black.log
        verbose: true
      - id: isort
        name: isort
        entry: isort project/
        language: system
        types: [python]
        require_serial: true
      - id: pyright
        name: pyright
        entry: pyright project/
        language: system
        types: [python]
        require_serial: true
