[tool.black]
line-length = 88
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  \.github/    # exclude a file named foo.py in the root of the project
)
'''

[tool.pyright]
include = ["project"]
exclude = ["**/__pycache__"]
typeCheckingMode = "basic"