name: Lint

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
  flake8:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: flake8
        run: flake8
  black:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: black
        run: black --check --diff .
  isort:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: isort
        run: isort --diff .
  mypy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: mypy
        run: mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers --no-pretty .
