# This is a good test for whether the model packaging works
# It's basically an end-to-end test of the pipeline as a whole,
# ensuring the 'all' workflow works and your model can be trained,
# assembled, and modeled
name: Validate Setup, Assemble, and Package

on:
  workflow_dispatch:

env:
  MODEL_NAME: en_stp_example

jobs:
  validate-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pip"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel
      - name: Install as editable package
        working-directory: ./project
        run: |
          pip install -e .
      - name: Assemble, Eval, Package
        working-directory: ./project
        run: spacy project run all --force
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-model
          path: ./project/package/**/*.whl

  validate-package:
    runs-on: ubuntu-latest
    needs: [validate-setup]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - uses: actions/download-artifact@v3
        with:
          name: packaged-model
          path: ./project/package
      - name: Install from wheel
        run: pip install $(find project/package -type f -name "*.whl" | head -n1)
      - name: Load model and run pipeline
        run: python -c "import spacy; nlp = spacy.load('${{ env.MODEL_NAME }}'); doc = nlp('this is some text'); print(doc.cats)"

  cleanup:
    runs-on: ubuntu-latest
    needs: [validate-package]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: packaged-model
